name: Weatherapp

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  setup:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest
